apiVersion: aptify/v1alpha1
kind: Repository
releases:
  - name: caido
    origin: caido.io
    label: Caido Desktop
    suite: caido
    components:
      - name: main
        packages:
          - packages/caido-desktop-v0.50.1-linux-aarch64.deb
          - packages/caido-desktop-v0.50.1-linux-x86_64.deb
